### ISSUE TITLE
Ausgabe: Graphen-Objekt als Adjazenzmatrix ausgeben (CSV-Datei / String für CSV-Date)

### ISSUE THREAD

**Issue by 089** [algdat/blatt-2-amf0#11]
1. Der aktuelle Zustand des Graphenobjekts ausgeben
1. als Adjazenzmatrix im CSV-Format

**Comment by 089** [comment]
Eventuell lässt sich diese Aufgabe gut mit den beiden in issue #9 genannten Features  get Adjazenzmatrix (bereits erledigt) und get Inzidenzmatrix kombinieren.

**Comment by 089** [comment]
@ForrestFalcon Da es bereits gemerged wurde können wir dieses Issue schließen oder ist noch etwas offen?

**Comment by kvn-stgl** [comment]
Schließen. Ich mach so etwas nur erst, wenn das ganze Zeug gemerged wurde.
