### ISSUE TITLE
Ausgabe: Graphen-Objekt als JSON im Format von http://sigmajs.org/

### ISSUE THREAD

**Issue by 089** [algdat/blatt-2-amf0#13]
1. Die interne Adjazenzmatrix wird als JSON ausgegeben
1. Format siehe http://sigmajs.org/ : "id" entspricht dabei dem Arrayindex der Adjazenzmatrix und Label aus dem "node name" Stringarray

**Comment by 089** [comment]
Bitte nach Absprache zwischen @Mniggl und @Areiser bei der Ausgabe bitte noch Folgendes ergänzen:
1. Eine Möglichkeit (z.B. überladene Methode) zusätzlich einen Teilgraphen bzw. Weg des Gesamtgraphen zu übergeben, der dann hervorgehoben wird (z.B. Farbe)
1. Übergebene Knotennamen (Array; Überladener Konstruktor wird noch durch @Areiser implementiert.) zuordnen und ebenfalls ausgeben. Standardmäßig werden die Knoten mit Zahlen vergeben. Damit sind auch beliebige Strings möglich. 
1. Überprüfen, ob das verwendete Tool (dot/graphviz bzw. sigmajs.org) gewichtete/bewertete Graphen unterstützt. Wenn ja ggf. implementieren (Das können wir aber gerne noch diskutieren).

**Comment by Mniggl** [comment]
Die Anforderungen habe ich heute noch einmal überprüft. In Sigmajs ist es grundsätzlich schon möglich eine Kantenbeschriftung einzuführen (hat auch zum Teil geklappt). Wenn man die Einführt, sind aber die Positionen der Knotenbeschriftungen verschoben...
