### ISSUE TITLE
Website für das Projekt inkl. Sourcecode-Dokumentation (Doxygen)

### ISSUE THREAD

**Issue by 089** [algdat/blatt-2-amf0#4]
1. Anforderung aus Aufgabenstellung
1. Hinweis: https://pages.github.com/#project-site
1. Jeder Entwickler schreibt für seine Methoden und Klassen sinnvolle **Doxygen-Kommentare** und **erläutert** in diesen etwaige **nicht-triviale Algorithmen**

**Comment by 089** [comment]
@ForrestFalcon Kannst du bitte noch so ne github.io page machen? 
Bzw. wollen wir das alles einfach auf Doxygen hauen?

**Comment by kvn-stgl** [comment]
@089 derzeit gibt es den Branch "gh-pages", welcher die Webseite live für dieses Repo anzeigt (wo auch die Doku rein gebaut wird). Würde dort auch die Webseite für die Graphenauswertung einbauen (siehe #50 ).

Welche Informationen hast du dir für github.io noch vorgestellt?

**Comment by 089** [comment]
@ForrestFalcon Ja, klingt gut. Schön fände ich außerdem die Verbindung mit #22 sodass wir dann unsere Webseite gleich für die Präsentation hernehmen können. Dafür wäre es gut, wenn die Webseite die Verwendung des Tools anhand eines kompletten Beispiels darstellt, also insbesondere: 

- [ ] Eingabe eines Graphen z.B. mittels Matlab-Notation #41 
- [ ] Aufruf der Option -na (siehe main.cpp)
- [ ] Aufruf einzelner/aller Funktionen mit Argumenten (siehe main.cpp)
- [ ] Ausgabe der Ergebnisse im Terminal (Screenshot) und der ggf. erstellten Dateien (JSON, DOT, HTML, ...)

**Comment by 089** [comment]
@ForrestFalcon @Mniggl Habe heute mit Marianus gesprochen, weil er sich nicht genau vorstellen konnte, was ich mit meiner Idee meine. Ein Beispiel, wie die Seite m.E. aussehen könnte wäre so:

# Graphs
Ein tolles Tool für und mit Graphen. Mit  diesem Tool können verschiedene Eigenschaften von Graphen ermittelt und ausgegeben werden. Die Ergebnisse werden übersichtlich dargestellt und können in verschiedenen Ausgabeformaten ausgegeben werden. Achte bei den Optionen auf Groß- und Kleinschreibung.

## Hilfefunktion
Mit `graphs --help` bzw. `graphs -h` lässt sich die Hilfefunktion aufrufen, die alle möglichen Optionen/Funktionen enthält und erklärt. Einen kleinen Auszug siehst du hier: 

```Bash

OPTIONS
    EINGABE

    -i     --input-csv          (1)
                Liest  die  Adjazenzmatrix  des  Graphen aus der angegebenen
                CSV-Datei aus.

    -iml   --input-matlab       (1)
                Erzeugt einen Graphen aus der in Matlab-Notation angegebenen
                Adjazenzmatrix.
[...]
    FUNKTIONEN OHNE ARGUMENTE

    -h     --help               (0)
                Zeigt die Hilfe an.

    -na    --no-args            (0)
                Ruft alle Funktionen auf, die keine Argumente benötigen und
                gibt die Ergebnisse aus.

    -V     --vertices-count     (0)
                Gibt die Anzahl der Knoten |V| aus.

    -E     --edges-count        (0)
                Gibt die Anzahl der Kanten |E| aus.
[...]
```

## Beispiel

### Eine Matrix in Matlab-Notation und alle Funktionen ausführt, die keine Argumente benötigen
`graphs -iml "[1 1 0; 1 0 1; 1 1 0]" -na -oj example.json

### Konsolen-Ausgabe des Ergebnisses
Da es nur einen Eingabegraphen gab, erhält dieser den Index 0.

```Bash
========================================
|         Ergebnisse Graph 0.          |
========================================
Anzahl Knoten                   : 3                               
Anzahl Kanten                   : 6                               
Ist gerichtet                   : ja                              
Ist vollstaendig                : nein                            
Ist ein Multigraph              : nein                            
Ist regulaer                    : nein                            
Ist einfach                     : nein                            
Hat einen Kreis                 : ja                              
Ist kreisfrei                   : nein   
```

### JSON-Ausgabe für SigmaJS
Der o.g. Befehl erzeugte unter anderem die Datei `0_example.json`. Die `0` steht für den Index des Graphen.

```JSON
{
  "nodes": [
    {
      "id": "0",
      "label": "0",
      "x": "3",
      "y": "6",
      "size": "1"
    },
    {
      "id": "1",
      "label": "1",
      "x": "7",
      "y": "5",
      "size": "1"
    },
    {
      "id": "2",
      "label": "2",
      "x": "3",
      "y": "5",
      "size": "1"
    }
  ],
  "edges": [
    {
      "id": "0",
      "source": "0",
      "target": "0",
      "type": "arrow",
      "size": "1"
    },
    {
      "id": "1",
      "source": "0",
      "target": "1",
      "type": "arrow",
      "size": "1"
    },
    {
      "id": "2",
      "source": "1",
      "target": "0",
      "type": "arrow",
      "size": "1"
    },
    {
      "id": "3",
      "source": "1",
      "target": "2",
      "type": "arrow",
      "size": "1"
    },
    {
      "id": "4",
      "source": "2",
      "target": "0",
      "type": "arrow",
      "size": "1"
    },
    {
      "id": "5",
      "source": "2",
      "target": "1",
      "type": "arrow",
      "size": "1"
    }
  ]
}
```
### Graph anzeigen mit SigmaJS

PLATZHALTER FÜR EINEN GANZ TOLLES BILD EINES GRAPHEN
