### ISSUE TITLE
Repo übernehmen?

### ISSUE THREAD

**Issue by obcode** [algdat/blatt-2-amf0#60]
Ich habe Ihnen Admin-Rechte in diesem Repo gegeben.

Sie können damit das Repo in ihren eigenen Account oder eine andere Organisation übernehmen.

Gehen Sie dazu auf Settings und scrollen Sie ganz nach unten. In der "Danger Zone" finden Sie "Transfer ownership".

Wenn Sie das Repo nicht übernehmen wollen, werde ich es Ende Juli löschen.

**Comment by 089** [comment]
:+1: gerne und schon passiert *gg*

**Comment by obcode** [comment]
👍
